### ISSUE TITLE
Lag Spike?

### ISSUE THREAD

**Issue by Roy416** [Nathat23/StackMob-3#157]
**Describe the bug**
After installing the latest version, there was a lag spike every 30 minutes, so at a fixed interval. We made sure it was StackMob since it started to have the lag at the fixed interval when we upgraded, and the lag stopped once we downgraded versions. 

**To Reproduce**
No steps, really

**Expected behavior**
No lag

**Screenshots/Videos**

**Bukkit/Spigot AND StackMob version:**
Paper Spigot 470 and 3.2.0
**Additional context**
 We have no idea why this is occuring, we are running 50+ players server and we would have no clue what mob is causing it but the timings says creeper or anything really about entities.
Here are the timings : https://timings.aikar.co//?id=12edd3dca1be4b13b096763e31d37292

**Comment by Nathat23** [comment]
Thanks for your ticket.

I'm guessing by the fact it is every 30 mins that it might be bStats causing this. Does disabling bStats in the **/plugins/bStats/config.yml** file prevent the issue?

**Comment by Roy416** [comment]
Yeah it doesnt lag anymore
