### ISSUE TITLE
Server Lag spikes from stackmob cache

### ISSUE THREAD

**Issue by Getblock** [Nathat23/StackMob-3#169]
**Describe the bug**
Server has occasional tick drops and found out due to repetitive testing of /timings.

https://timings.aikar.co/?id=3d64a387ea3849e48d0aac0ca8173ea0
![image](https://user-images.githubusercontent.com/43926892/50380927-772f1e00-06b3-11e9-8b44-d1f4e1187407.png)

we are stable 20 but drops to 3-15... anywhere around those TPS.

**Bukkit/Spigot AND StackMob version:**
Self explanatory.
paperclip 1.13.2
StackMob v3.2.0

![image](https://user-images.githubusercontent.com/43926892/50380928-9e85eb00-06b3-11e9-861a-929b58e1c21b.png)
It might be because there is a alot of cached entities? i don't know, is there a way to remove all "Hostile Mobs" Cached entities.

**Comment by Nathat23** [comment]
I'm guessing this many be somewhat linked to #168 and #150 
Garbage data isn't getting removed and it gets set on entities that shouldn't have it, single entities are also clogging up your cache. The above commits should help massively.

**Comment by LogGits** [comment]
Would there be a way to periodically run that method of cleanup? e.g. When the server stops, remove from the 0's or -1's from cache.

**Comment by Nathat23** [comment]
the command will only  need to be ran once. the single stacks will no longer be cached when chunks unload.
