### ISSUE TITLE
Stacking question

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-3#171]
If i set it to allow stacking on breeding, how does it stack/unstack correctly. Do they unstack until they are allowed to breed again?

**Comment by Nathat23** [comment]
which config option are you referring to?

**Comment by LogGits** [comment]
Not really a config option im just asking about how breeding works with stacking. Because i saw players breed mobs. The mobs would unstack and breed with other mobs then stack again. This allows an endless loop of breeding.

**Comment by Nathat23** [comment]
The mobs should split from the original stack, breed, then restack into another stack which cannot breed.

**Comment by LogGits** [comment]
Ah ok awesome, And how long does it take that stack to be breed-able again?

**Comment by Nathat23** [comment]
"for about 5 minutes" according to https://minecraft.gamepedia.com/Breeding
