### ISSUE TITLE
"spawner" reason doesn't work?

### ISSUE THREAD

**Issue by Roy416** [Nathat23/StackMob-3#174]
**Describe the bug**
Natural spawning mobs are still stacking, even though i put 'spawner' as the only stack reason, and 'natural' a reason to why it shouldnt stack. I put a list of hostile mobs that i want to stack from a spawner, but now some natural hostile mobs are stacking. 
**To Reproduce**
I put "spawner" as the only "stack-reason", meaning only mobs that come from the spawner will stack. I also put "Natural" and other variables for "no-stack-reasons", so natural spawning mobs will not stack. I added in the list of hostile mobs I want to stack. put "dont-stack-until" to 2. restarted server, natural hostile mobs start to stack. same issue with unhostile mobs. 
**Expected behavior**
Only the mobs that come out of a spawner should stack. and natural spawning mobs should not stack at all since it is specified in the "no-stack-reasons" 

**Screenshots/Videos**
https://imgur.com/a/spHN03Z
**Bukkit/Spigot AND StackMob version:**
Paper Spigot  470 , 1.13.2 and stack mob version: 3.3.1
**Additional context**

**Comment by Nathat23** [comment]
could you pastebin your entire config.yml file so that I can test it?

**Comment by Roy416** [comment]
https://pastebin.com/1i5jSsu1

**Comment by Nathat23** [comment]
This is an issue with entities being restacked on chunk load. Has been fixed.
