### ISSUE TITLE
kill-step-damage error

### ISSUE THREAD

**Issue by osybear1** [Nathat23/StackMob-3#175]
**Describe the bug**
Enabling kill-step-damage causes this error.
Then killing a single mob of a stack causes the error to pop up. 

**To Reproduce**
Enable kill-step-damage in config. Kill a stack of mobs and it should pop up.

**Expected behavior**
Not sure if the error causes drop and xp problems

**Screenshots/Videos**
https://pastebin.com/gaheFdr2

**Bukkit/Spigot AND StackMob version:**
Self explanatory.
[22:05:49] [Server thread/INFO]: This server is running Paper version git-Paper-477 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Additional context**
Not sure if this problem causes anything bad but just throwing it up for a fix

**Comment by Nathat23** [comment]
Fixed.
