### ISSUE TITLE
Cache File

### ISSUE THREAD

**Issue by Getblock** [Nathat23/StackMob-3#176]
**Describe the bug**
I have a cache file that is overly big size. can you change the Database storage that is super efficient in looking up big storages and maybe even a MySQL or SQlite

![image](https://user-images.githubusercontent.com/43926892/50465551-f3d33c80-09d2-11e9-9944-5cb726fb17fc.png)

Looking up through the whole file lags the server itself. Imagine having to always check that big chunk of a file every so minutes, it's devastating.

**Comment by Getblock** [comment]
Can you make it save async also? do not use the main thread for saving it.

**Comment by Nathat23** [comment]
run the command '/sm cleanup' to remove all the single stacks. the saving is done async.

**Comment by Getblock** [comment]
Still lags the server, currently i have over 8,000,000 stacked entities and server is reaching 90+ daily.... 

Saving cache thing still cause tick drops. I'm probably one of the few medium size servers that uses your plugin in which probably why no one has reported this yet. (This problem will only occur on big player bases)
![image](https://user-images.githubusercontent.com/43926892/50552968-08684b00-0cd9-11e9-9bba-02c4cf52cd81.png)

**Comment by Getblock** [comment]
I have started using MySQL but still is the same problem.

**Comment by Getblock** [comment]
![image](https://user-images.githubusercontent.com/43926892/50603582-f1527480-0ef5-11e9-8634-043626e3f3cb.png)
can you also add /sm cleanup on the loaded mobs?

**Comment by Nathat23** [comment]
Do you have a plugin that keeps chunks loaded or something?

**Comment by Getblock** [comment]
Yeah i feel like i know why you asked that, the loaded entities never goes to cached entities even if the chunk gets unloaded

**Comment by Getblock** [comment]
![image](https://user-images.githubusercontent.com/43926892/50604764-f49c2f00-0efa-11e9-895d-0f7229b57075.png)

So i restarted my server just to fix the issue and currently i'm not even sure why the number is higher than the Stacked but it fixes it after /sm cleanup

**Comment by Nathat23** [comment]
I'm guessing that you have a lot of junk data that wasn't removed properly in some earlier versions.

The only way to fix this would be to drop the stackmob table, so that all data is removed. Then add a plugin (which i'm making rn) to recreate the data for entities when chunks load.

Can you provide your config.yml file?

**Comment by Nathat23** [comment]
Here you go:
https://drive.google.com/open?id=1gEOXomVRw7CAsbMPE_0TkXU_23cqGVlf
Stop the server, drop the stackmob table, add the above plugin, then restart the server.

**Comment by Getblock** [comment]
I'm guessing this will remove all the existing mobs?

**Comment by Nathat23** [comment]
When you drop the table it will remove the stack information, but not the mobs. The plugin above will reapply the stack information when chunks load.
