### ISSUE TITLE
Metadata of entities removed by plugin or server are never cleared

### ISSUE THREAD

**Issue by MedicOP** [Nathat23/StackMob-3#184]
Entities that are killed by other plugins using Entity.remove(), or ones that are despawned by Minecraft are never removed from the world's metadata store resulting in memory leak.

For servers that use plugins like this, for example the plugin ChunkSpawnerLimiter which limits the amount of mobs you can have in a chunk, this can quickly lead to out of memory errors.

**Comment by SmallSansSerif** [comment]
Can the author comment on this? Why does saving entity amount storage take so long when stopping server now too?
