### ISSUE TITLE
Xp drop

### ISSUE THREAD

**Issue by jordyvandijken** [Nathat23/StackMob-3#186]
**Describe the bug**
Mobs seems always to drop xp when they die. and when they die without the player killing. The xp drops but it will add 0 xp to the player

**To Reproduce**
Let them die of falling or anything else without hitting

**Expected behavior**
Only to drop xp when the player kills them

**Screenshots/Videos**
https://youtu.be/hnEriYoMBF4

**Bukkit/Spigot AND StackMob version:**
Spigot - Stackmob-3.3.2 - mc 1.13.2

**Comment by Nathat23** [comment]
unless I'm mistaken, don't mobs have to be killed by players to drop exp?

**Comment by Nathat23** [comment]
closing as no response.
