### ISSUE TITLE
Boss by Kangarko compatibility

### ISSUE THREAD

**Issue by ArathiaMC** [Nathat23/StackMob-3#187]
Hello,

I'd like support to the Boss plugin by Kangarko so these custom monsters do not stack, similarly to the MythicMobs option already present with the plugin.
https://www.spigotmc.org/resources/limited-sale-%E2%98%9B-boss-unbelievable-custom-monsters-1-8-9-1-13-2.46497/

Thank you :)

**Comment by Nathat23** [comment]
Considering that is a paid plugin, I would suggest about asking the author of that plugin about support, since I'm not going to receive any benefit from it.
