### ISSUE TITLE
API to get count of stacked entities

### ISSUE THREAD

**Issue by Rukes** [Nathat23/StackMob-3#189]
In previous version there was entity metadata `stackmob:stack-size` to get count of stacked entities. In 1.13 version it does not work. Would be nice to add back of fix.

**Comment by Nathat23** [comment]
use the API.
`StackMob sm = (StackMob) Bukkit.getPluginManager().getPlugin("StackMob");
EntityManager em = new EntityManager(sm);
int size = em.getStackedEntity(entity).getSize()`
