### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by JustNopsit** [Nathat23/StackMob-3#192]
**Describe the bug**
When StackMob saves entity amount storage, it throws OutOfMemoryError exception, kicks few players out of server and creates humongous files (up to 900MB (our whole server has only 5.4GB)).

**To Reproduce**
Have StackMob save entity amount storage.

**Expected behavior**
save files without using all the RAM.

**Screenshots/Videos**

**Bukkit/Spigot AND StackMob version:**
Spigot 1.13.2
StackMob 3.3.2

**Additional context**
https://pastebin.com/raw/LWTerLi7

**Comment by Nathat23** [comment]
Does running '/sm cleanup' help at all?

**Comment by Nathat23** [comment]
Related to #184
