### ISSUE TITLE
Server hangs while saving to mysql db

### ISSUE THREAD

**Issue by wolfgang784** [Nathat23/StackMob-3#195]
Hello. Every time I try to stop my server it gets hung up on 

[10:11:59 INFO]: [StackMob] Disabling StackMob v3.3.2
[10:11:59 INFO]: [StackMob] Cancelling currently running tasks...
[10:11:59 INFO]: [StackMob] Saving entity amount storage...

For like 10+ minutes before it finally finishes. Sometimes it doesn't ever finish and I need to just close the cmd window, which causes other things to roll back since stackmobs is one of the first plugins to try to save. I tried adding stackmobs to my mysql server but the issue persists. The server is not even live yet, still in development, so its not like there are tens of thousands of mobs in stacks or anything. My server certainly has plenty of resources for what I am trying to do as I am running:

i7-7700k quad core (8 threads) at 4.2GHz
48GB ddr4 2133MHz ram
500GB samsung 860 evo ssd

I am running the current newest version of paper spigot and of stackmobs along with a handful of other plugins that I can PM to a dev at request.

**Comment by Nathat23** [comment]
Related to #184
