### ISSUE TITLE
Stack Number Messed Up.

### ISSUE THREAD

**Issue by ZephyrusHQ** [Nathat23/StackMob-3#196]
![2019-03-10_17 26 34](https://user-images.githubusercontent.com/48419244/54091752-0dd9b580-435a-11e9-9271-c4b087a87828.png)

Stack Numbers Messed Up - Updated 10 Minutes Ago.

**Comment by Nathat23** [comment]
can you provide your config.yml? it looks like you have the color char in the wrong place.

**Comment by ZephyrusHQ** [comment]
Oh, hey! I fixed it but appreciate it!

Andrew Watson

________________________________

**Comment by Nathat23** [comment]
okay then, closing.
