### ISSUE TITLE
Villager Cartographer Bug

### ISSUE THREAD

**Issue by BiGUNMAN** [Nathat23/StackMob-3#197]
**Describe the bug**
When villagers stack, they always become cartographers instead of stacking based on profession. Even though I have this config option set to true.

**To Reproduce**

**Expected behavior**
Villagers to stack seperately

**Bukkit/Spigot AND StackMob version:**
Paper: 525
StackMob: 3.3.2

**Additional context**
Config: `compare:
  villager-profession: true`

**Comment by Nathat23** [comment]
Could you provide an image(s) or a video of showing this?

**Comment by Nathat23** [comment]
closing as no response.
