### ISSUE TITLE
Summoned mobs deleting after restart | cosole flood

### ISSUE THREAD

**Issue by HauserGrim** [Nathat23/StackMob-3#202]
When mobs summoned from eggs/summon command create console flood and delete summoned mobs after restart

Steps to reproduce:
Start server
Join to the server
Take mob spawn egg
Summon some mobs and wait stacking
Look at console warn flood (https://pastebin.com/GcQvFDWy)
Restart server
Summoned mobs are deleted

Paper 1.13.2 build 566 (latest)
StackMob v3.3.3

**Comment by Nathat23** [comment]
In the config.yml file, do you have "use-translation" under "tag" enabled?

**Comment by HauserGrim** [comment]
no

**Comment by Nathat23** [comment]
do you have mythicmobs?

**Comment by HauserGrim** [comment]
Oh, yes

**Comment by HauserGrim** [comment]
Is this due to MM API changes?
Will this be fixed in the next SM release?

**Comment by HauserGrim** [comment]
I checked different versions and configurations of MM and found the reason
If i add mob to VaniilaMobs.yml and add drop or edit HP in this mob it causes a bug with this mob

**Comment by HauserGrim** [comment]
compiled sources, summoned mobs edited in VanillaMobs continue to be deleted after restart

**Comment by HauserGrim** [comment]
Sorry, "Despawn" option default by true in MM.
It was necessary to add Despawn: false option to mob

CAVE_SPIDER:
  Options:
    PreventRenaming: false
    PreventLeashing: false
    Despawn: false
