### ISSUE TITLE
When feeding bug

### ISSUE THREAD

**Issue by niko411** [Nathat23/StackMob-3#203]
**Describe the bug**
When feeding stacked animals, errors pour in the console

**To Reproduce**
Right click in a stacked animal

**Expected behavior**
Breeding animals

**Bukkit/Spigot AND StackMob version:**
git-Paper-493
StackMob v3.3.3

**Additional context**
pastebin - https://pastebin.com/neZrkp9Y
[latest.log](https://github.com/Nathat23/StackMob-3/files/2985494/latest.log)

**Comment by Nathat23** [comment]
You need to update paper.
