### ISSUE TITLE
MAJOR BUG - Stacked Mobs Losing their Stack Amounts! Related to Chunkborders?

### ISSUE THREAD

**Issue by BoozleDoof** [Nathat23/StackMob-3#207]
**Describe the bug**
Multiple Mob Stacks located within a single chunk are not being saved properly.
If there are 2 or more stacks of mobs, regardless of mob type and number of stacked mobs, upon returning to the chunk with the stacked mobs after leaving/unloading the chunk for some time (tested every 2 minutes), only 1 stack of mobs remained while the other stacks continued to have the nametag of their amounts, but in reality were no longer stacked, a single unstacked mob.

**To Reproduce**
- Move far enough away from spawn to chunks that will unload.
- Enable Show Chunk Borders.
- Create two small fenced in areas for the mobs within a single chunk.
- Create a stack of mobs using any means inside both fenced in area.
- Create one small fenced in area for a 3rd stack of mobs within a single chunk next to the chunk you just built within.
- Create a stack of mobs using any means inside this new area.
- Wait 120s for the database to save. (Possibly not necessary)
- Leave the area far enough away to unload the chunks.
- Wait 120s for the database to save again. (Again, possible not necessary)
- Return to the chunks you spawned mobs into.
If done this way, the chunk with 1 stack of mobs inside of it will have retained its correct stack amount while within the chunk containing two stacked mobs, one stack will have lost its stack amount while the other will have retained its correct stack amount.

**Expected behavior**
All stacked mobs should retain their stack amounts when leaving a chunk, regardless of how many different stacked mobs there are within a single chunk.

**Screenshots/Videos**
![javaw_2019-04-11_21-18-55](https://user-images.githubusercontent.com/40279667/56014059-8bba1500-5ca8-11e9-8dc2-70ac959274eb.jpg)
![javaw_2019-04-11_21-27-08](https://user-images.githubusercontent.com/40279667/56014060-8bba1500-5ca8-11e9-900f-5af373d39ab9.png)
![javaw_2019-04-11_21-36-25](https://user-images.githubusercontent.com/40279667/56014061-8bba1500-5ca8-11e9-9f6b-464cb6959c81.jpg)
![javaw_2019-04-11_21-41-27](https://user-images.githubusercontent.com/40279667/56014062-8bba1500-5ca8-11e9-9ac5-e218a43edded.jpg)
![javaw_2019-04-11_21-47-10](https://user-images.githubusercontent.com/40279667/56014063-8bba1500-5ca8-11e9-9d69-33229fe522dd.png)
![javaw_2019-04-11_21-52-18](https://user-images.githubusercontent.com/40279667/56014065-8c52ab80-5ca8-11e9-96d0-592270622e7a.png)
![javaw_2019-04-11_22-02-04](https://user-images.githubusercontent.com/40279667/56014066-8c52ab80-5ca8-11e9-9811-5e10a7d44b01.jpg)
![javaw_2019-04-11_22-07-47](https://user-images.githubusercontent.com/40279667/56014067-8c52ab80-5ca8-11e9-9f9c-8497696f9774.jpg)

**Bukkit/Spigot AND StackMob version:**
Paper Version: git-Paper-572 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
StackMob Version: 3.3.4

**Additional context**
When a stacked mob loses its stack in these cases...
The mob remains named with the amount it had previously.
The mob, when inspected using the Stick of Stacking's DATA feature shows a UUID.
The mob, when inspected using the Stick of Stacking's DATA feature DOESN'T show a stack-size, not even a -1 stack size, it just isn't there.

**Comment by Nathat23** [comment]
Thanks for the detailed bug report.
