### ISSUE TITLE
Breeding MUSHROOM_COW doesn't produce offspring.

### ISSUE THREAD

**Issue by BoozleDoof** [Nathat23/StackMob-3#211]
**Describe the bug**
Breeding a stack of Mooshrooms will produce hearts, but no offspring, when the config is set to spawn a stack of baby mobs on breed.

**To Reproduce**
+ Summon in a stack of Mooshrooms, 10 for example.
+ Use a stack of wheat on the 10x Mooshroom Stack.
Hearts will appear, but no offspring will be produced.

**Expected behavior**
Produce a stack of baby Mooshroom equal to 1/2 of the parent's stack size, rounded down.

**Screenshots/Videos**
![Mooshroom_Breed_Bug](https://user-images.githubusercontent.com/40279667/56326759-365c8880-612c-11e9-8995-9035b6723143.gif)
![Stack DataStick](https://user-images.githubusercontent.com/40279667/56326370-a10cc480-612a-11e9-93a8-249d779b2bf1.png)

**Bukkit/Spigot AND StackMob version:**
PaperMC: git-Paper-616 (MC:1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
StackMob: 3.3.6

**Additional context**
Configuration File of Testing Environment
https://pastebin.com/dtUGJ3xj

**Comment by Nathat23** [comment]
Fixed in commit above.
