### ISSUE TITLE
NoSuchMethod Error

### ISSUE THREAD

**Issue by heyyitstim** [Nathat23/StackMob-3#214]
**Describe the bug**
Ongoing error that fills the server console.

**To Reproduce**
Load the plugin and start the server.

**Expected behavior**
I expected it to not fill the console with errors.

**Screenshots/Videos**
No screenshot or video, but a pastebin link: https://pastebin.com/hrSfKzdH

**Bukkit/Spigot AND StackMob version:**
Spigot 1.13.2, StackMob 3.3.6

**Comment by Nathat23** [comment]
You need to update spigot.
