### ISSUE TITLE
Curing zombie villagers.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-3#225]
Recently got the following report:

> Brief Description: Used a potion of weakness, and then a golden apple to cure a stack of 3 zombie villagers. The cure worked for the first one, however it remained stacked with the zombie villagers. 
> 
> Instructions: Find a stack of zombie villagers. Attempt to cure them.
> 
> How many times did you recreate this?: Once
> 
> Result: The villager remained stacked with the zombie villagers.
> 
> Expected Result: The villager should unstack from the zombie villagers to allow me to cure the rest.

I'm using the 1.12.2 version of Stack Mobs. Is there something I can do via config to have cured zombie villagers unstack from the stack, or is this a bug that was fixed in a future Stack Mobs version and there's nothing I can do?

**Comment by Nathat23** [comment]
The event to listen to the conversion of entities was unfortunately only added in 1.13.
