### ISSUE TITLE
task-delay does not work

### ISSUE THREAD

**Issue by Leomelonseeds** [Nathat23/StackMob-3#226]
As described in the title, the task-delay configuration option does not work. I've set it to 40, yet mobs are still stacking at the default rate of 100. Please fix this soon, thanks.

**Comment by Nathat23** [comment]
Did you fully stop/start the server?

**Comment by Leomelonseeds** [comment]
Yes I did. I believe this is caused by this piece of code:

![image](https://user-images.githubusercontent.com/17891302/57985289-87f17f00-7a1a-11e9-8e37-4a87ed848a44.png)

If you swap peroid and 100 I think it should work.

Thanks.
