### ISSUE TITLE
Baby animal dropping loot when kill

### ISSUE THREAD

**Issue by DeftFury** [Nathat23/StackMob-3#229]
**Is your feature request related to a problem? Please describe.**

When baby animal are stack and get kill they drop loot (baby animal are not suppose to drop any loot in vanilla)

**Describe the solution you'd like**

It will be nice to have an option in the config that you can allow or not the fact that baby animal drop loot when killed.

I have also found that when a lot of baby are stack they will grow into adult faster and all in 1 shot. (i dont know if it will be possible to keep the real grow time of an animal)

Very nice plugin that i will love to put on my serv if the baby animal loot probleme can be resolve :)

Thanks You

**Comment by Nathat23** [comment]
fixed in above.
