### ISSUE TITLE
defaults folder added to config?

### ISSUE THREAD

**Issue by CaszGamerMD** [Nathat23/StackMob-3#233]
**Describe the bug**
on fresh load of stack mob 4.0.0, a defaults folder is loaded into the config folder, i don't think that is supposed to be there

**To Reproduce**
load fresh 4.0.0 i havent tried from previous version as im making a all out new server with friends

-removed defaults folder and on reboot it repopulates.
doesn't seem like the default folder plays any role with loaded configs

**Expected behavior**
i dont think the defaults folder should be there, im ok if thats wrong.

**Screenshots/Videos**
![Screen Shot 2019-06-04 at 1 44 36 AM](https://user-images.githubusercontent.com/37286039/58857295-75a65080-866a-11e9-9723-9713ae295d74.png)

**Bukkit/Spigot AND StackMob version:**
1.14.2 PAPER, stackmob 4.0.0

**Additional context**
i think thats all...

**Comment by Nathat23** [comment]
That's by design, so that when the config is updated and the comments removed you can use the default files for reference.
