### ISSUE TITLE
SM4 hates magma blocks

### ISSUE THREAD

**Issue by CaszGamerMD** [Nathat23/StackMob-3#234]
**Describe the bug**
just filling console with this error, doesnt seem to have any ingame bugs, _in pastebin_

tested on server, no mob drop issues that i can see.

**To Reproduce**
[mob] dies on magma blocks

**Expected behavior**

**Screenshots/Videos**
https://pastebin.com/PESSGShR
[config.txt](https://github.com/Nathat23/StackMob-3/files/3251089/config.txt)
added config in case,
**Bukkit/Spigot AND StackMob version:**
1.14.2, SM4.0
**Additional context**

**Comment by Nathat23** [comment]
sorry for a really late reply. do you know what mob caused this?

**Comment by CaszGamerMD** [comment]
slime

**Comment by Nathat23** [comment]
thank you so much - this is a bug in spigot so I will have to report it there.

**Comment by Nathat23** [comment]
this has just been fixed in craftbukkit - https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/660b6d19a7fed4fdbc93ed4895eb772860cfd781

update your server to solve your issues, may be a while though until paper pushes an update.
