### ISSUE TITLE
Can't shear sheep

### ISSUE THREAD

**Issue by masonmanley** [Nathat23/StackMob-3#240]
**Describe the bug**
Stacked sheep cannot be sheared

**To Reproduce**
1. Stack sheep
2. Try to shear them
**Expected behavior**
The sheep should drop an amount of wool equivalent to the stack size e.g. 13 sheep = 13 pieces of wool when sheared
**Screenshots/Videos**
N/A
**Bukkit/Spigot AND StackMob version:**
SM: 4.0.0
Server: Paper 80

**Comment by masonmanley** [comment]
Update: this occurs when using Grief Prevention. When going into someone else's claim and using /ignoreclaims. Sheep cannot be sheared.

This is fairly low priority I guess, but thought I'd report it.

**Comment by Nathat23** [comment]
related to #227
