### ISSUE TITLE
Option to disable certain mobs from stacking all together

### ISSUE THREAD

**Issue by magmiy** [Nathat23/StackMob-3#248]
This is one of the only MobStacking plugins for 1.14 and I think it would be beneficial to add more features.

Make it so you can go into the config file and type certain mobs into a list so they will be completely ignored by the MobStacking plugin.

**Comment by Aurelien30000** [comment]
It seems that is already the case : https://github.com/Nathat23/StackMob-3/blob/master/Plugin/src/main/resources/config.yml#L70
