### ISSUE TITLE
Error with your last update

### ISSUE THREAD

**Issue by jere62smi** [Nathat23/StackMob-3#249]
Error with your last update: https://pastebin.com/VHnpdBjh

**Comment by Aurelien30000** [comment]
How could you reproduce that (step by step if possible) ? :)
Thanks

**Comment by jere62smi** [comment]
I just put the .jar and started the server, there was no prior config file, everything was generated as if I had just put the plugin for the first time.

**Comment by Aurelien30000** [comment]
Are all the files generated, does the error reoccur during the another reboot ?

**Comment by jere62smi** [comment]
Yes the files are loaded correctly. The error is no longer there after one/or more reboots.

**Comment by Aurelien30000** [comment]
It doesn't seem really important to me and I didn't even manage to reproduce it.
Keep this issue opened for Nathan :)

**Comment by Nathat23** [comment]
Fixed in above commit.
