### ISSUE TITLE
HELP! is not dropping multiplied items and generates error in console

### ISSUE THREAD

**Issue by TiagoBrazil** [Nathat23/StackMob-3#256]
**Describe the bug**
Is'nt dropping multiplied items and generates error in console (XP too)
http://prntscr.com/ofdm6v

Console error: http://prntscr.com/ofdmmz

V1.14

**To Reproduce**

**Expected behavior**

**Screenshots/Videos**

**Bukkit/Spigot AND StackMob version:**
Self explanatory.

**Additional context**

**Comment by Nathat23** [comment]
Duplicate of  #243
