### ISSUE TITLE
[StackMob] Task #17 for StackMob v4.0.2 generated an exception

### ISSUE THREAD

**Issue by magmiy** [Nathat23/StackMob-3#262]
24.07 23:54:09 [Server] WARN [StackMob] Task #17 for StackMob v4.0.2 generated an exception
24.07 23:54:09 [Server] INFO java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
24.07 23:54:09 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) ~[?:?]
24.07 23:54:09 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
24.07 23:54:09 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
24.07 23:54:09 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
24.07 23:54:09 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
24.07 23:54:09 [Server] INFO at uk.antiperson.stackmob.compat.hooks.ProtocolLibHook.sendPacket(ProtocolLibHook.java:52) ~[?:?]
24.07 23:54:09 [Server] INFO at uk.antiperson.stackmob.tasks.ShowTagTask.run(ShowTagTask.java:42) ~[?:?]
24.07 23:54:09 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[Paper-1.14.4-b137.jar:git-Paper-137]
24.07 23:54:09 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[Paper-1.14.4-b137.jar:git-Paper-137]
24.07 23:54:09 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1144) ~[Paper-1.14.4-b137.jar:git-Paper-137]
24.07 23:54:09 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[Paper-1.14.4-b137.jar:git-Paper-137]
24.07 23:54:09 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1076) ~[Paper-1.14.4-b137.jar:git-Paper-137]
24.07 23:54:09 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:920) ~[Paper-1.14.4-b137.jar:git-Paper-137]
24.07 23:54:09 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

This has been occurring after I updated to Paper 1.14.4...

**Comment by rizkiherda** [comment]
Me too, now I'm using Spigot 1.14.4...

**Comment by Maelep** [comment]
I got this error since I enabled:
`  # Only show the name tag if the player is near the entity. (requires ProtocolLib)
  show-player-nearby:
    enabled: true`

I think it's a compatibility problem with ProtocoLib.

**Comment by Aurelien30000** [comment]
Try to update ProtocolLib to his latest dev version, designed for 1.14.x :) http://ci.dmulloy2.net/job/ProtocolLib Gradle/lastSuccessfulBuild/
